# Generated by Django 4.1 on 2024-10-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoorDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="door_detections/")),
                ("result", models.CharField(max_length=255)),
            ],
        ),
    ]
